template = '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: packer
  name: packer
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: hashicorp/packer
    name: packer
    '''

def buildNumber = env.BUILD_NUMBER


if (env.BRANCH_NAME == "main") {
    kaizen = "us-east-1"
    type = "t2.micro"
    key = "my laptop key"
}

else if (env.BRANCH_NAME == "dev") {
    kaizen = "us-east-2"
     type = "t3.micro"
    key = "my laptop key"
}

else if (env.BRANCH_NAME == "qa") {
    kaizen = "us-west-1"
     type = "t2.small"
    key = "my laptop key"
}

else {
    error "Branch doesn't not supported"
}

podTemplate(cloud: 'kubernetes', label: 'packer', showRawYaml: false, yaml: template){
node("packer"){
container("packer"){

stage ("Checkout SCM") {
    git branch: 'main', url: 'https://github.com/kaizenacademy/jenkins-july.git'
}

withCredentials([usernamePassword(credentialsId: 'aws-creds', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
withEnv(["AWS_REGION=${kaizen}"]) {

stage("Packer"){
  sh """
  cd packer
  packer init .
  packer build -var 'jenkins_build_number=${buildNumber}' packer.pkr.hcl
  """

  build job: 'hello-world', 
  parameters: [
    string(name: 'action', value: 'apply'), 
    string(name: 'region', value: "${kaizen}"), 
    string(name: 'ami_id', value: "my-ami-${buildNumber}"), 
    string(name: 'type', value: "${type}"), 
    string(name: 'az', value: "${kaizen}b "), 
    string(name: 'key', value: "${key}")]
}
}
}
}
}
}
